project:
  type: website

website:
  title: "The James Lab"
  favicon: "images/JamesLabLogo_Small.png"
  navbar:
    collapse: true
    left:
      - href: index.qmd
        text: Home
      - href: news.qmd
        text: News
      - href: people.qmd
        text: People
  search: 
    location: navbar
    type: overlay
    limit: 5
    copy-button: true


page-footer:
  border: false
  background:
  foreground:
  left: "2024"
  right: 
    - 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



