project:
  type: website

website:
  title: "The James Lab"
  favicon: "images/JamesLabLogo_Small.png"
  search: false
  navbar:
    collapse: true
    logo: "images/JamesLabLogo_Small.png"
    logo-href: https://www.jameslab.ca
    left:
      - href: https://www.jameslab.ca/projects
        text: Projects
      - href: people.qmd
        text: People
      - href: https://www.jameslab.ca/publications
        text: Publications
      - href: https://www.jameslab.ca/teaching
        text: Teaching
      - href: news.qmd
        text: News
      - href: https://www.jameslab.ca/contact
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



